name: ShelfStory
description: A vintage-style personal book tracking app
publish_to: 'none'
version: 1.5.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Utilities
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  
  # Barcode Scanner
  mobile_scanner: ^3.5.5
  
  # HTTP for Google Books API
  http: ^1.1.2
  
  # CSV Export
  csv: ^5.1.1
  
  # Image Picker
  image_picker: ^1.0.7
  
  # Animations
  flutter_staggered_animations: ^1.1.1
  
  # Fonts
  google_fonts: ^6.1.0

  # Icons
  cupertino_icons: ^1.0.6
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  google_sign_in: ^6.2.1
  fl_chart: ^0.68.0 
  http: ^1.2.0  # For Google Drive API

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#5D2E0F"  # Dark brown color
  adaptive_icon_foreground: "assets/images/app_icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/

